language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIT4X4NDGM2WVL6VA
  - DOCKER_USERNAME=octoblu
  - DEPLOY_APPLICATION_NAME=octoblu-oauth-provider
  - DEPLOY_REGION=us-west-2
  - DEPLOY_BUCKET=octoblu-deploy
  - DEPLOYMENT_GROUP=master
  - DEPLOY_KEY=octoblu-oauth-provider/octoblu-oauth-provider-$TRAVIS_COMMIT.zip
  - secure: yUG5O4e1zlh3lsU5Y84zOXLWxkIr0PJNyaCHdcniPlOQJ2muMMsLT85cXMmelhhTy0BGxsNU+fV2xn4RIaUNogJwt6pn4iSuNAQTzBqMNU4qohnf/niUfGmn2MiJ/FuwEBZmNh5PwUuvdtRjzP2FjJC+SCK3m/rb5csvQsBQ6QM=
  - secure: i4QNeYl8ScrL14VtYGzM1nfy4OS5b5hr9ungAfKp0DXU3+29Rtr2r70KNwlvowEBH070qJTypfuKU40oIzZDsaOy45/EegVdKQdG/1okvHWWkZDD2dUOk52sYaysa5+FlGFqRAL7hUNDEjkoxbpKwE3g7rVLAw4iDiPqDh6rXHo=
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: &1
    secure: kxW3HRaVMIqX5ZY/POsaKGjqNptsgYDtuPQiNdJ24jkvRDnjHNwpxfh2bzUbGKyZZyofXWaBYDNc3AviyYImjT+vdeeQePYkfS10sfCKb5ePln8uvhs8aKhaapeWm5PeBDrvY3URvsJef1o55uO2gflk56b33G1gA1kysNPo/tY=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: docker-builder/octoblu-oauth-provider-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: docker-builder
  deployment_group: octoblu-oauth-provider
  on:
    branch: master
